source 'http://rubygems.org'

gem 'vagrant'
gem 'puppet'
gem 'rake'
gem 'guard'
gem 'guard-rake'
gem 'growl_notify'
gem 'vagrant-sync'
gem 'librarian-puppet', :git => 'https://github.com/benburkert/librarian-puppet.git'
